const { chromium }=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.clock.install();await page.goto(process.env.PLAYTEST_URL || require('node:url').pathToFileURL(require('node:path').resolve(__dirname,'../index.html')).href);await page.clock.runFor(200);
const snap=()=>page.evaluate(()=>climb.snapshot()),wait=ms=>page.clock.runFor(ms),button=i=>i?'right':'left';
async function aim(id){const p=await page.evaluate(id=>climb.screen(id),id);await page.mouse.move(p.x,p.y);}
async function key(k){await page.keyboard.press(k);await wait(30);}
async function release(i){await page.mouse.move(150,450);await page.mouse.down({button:button(i)});await page.mouse.up({button:button(i)});}
async function place(id,i){await page.mouse.down({button:button(i)});assert.equal((await snap()).hands[i],null,'press frees the hand immediately');await wait(1000);await aim(id);let moving=await snap();assert.equal(moving.moving[i],true);assert.equal(moving.hands[i],null,'moving onto ring never grabs before release');await page.mouse.up({button:button(i)});let s=await snap();assert.equal(s.hands[i]?.id,id,`grab ${id}: ${JSON.stringify(s.player)}`);await wait(800);}
await aim(3);await page.mouse.down();await page.mouse.up();assert.equal((await snap()).hands[0],null);assert.match(await page.locator('#toast').innerText(),/OUT OF REACH/);
await place(0,0);await page.screenshot({path:'tests/short-arms.png'});
for(let id=1;id<15;id++){await place(id,id%2);if(id===6)await page.screenshot({path:'tests/cliff-mid.png'});}
await release(1);await wait(1000);await release(0);await wait(2000);assert.equal((await snap()).won,true,'main route settles on summit');console.log('MAIN ASCENT PASS');await page.screenshot({path:'tests/summit.png'});
await key('r');for(let id=0;id<=4;id++)await place(id,id%2);await release(1);await wait(1000);const before=await snap();await release(0);await wait(230);let falling=await snap();assert.ok(falling.player.y>before.player.y+10);assert.ok(falling.player.vy>100);await aim(3);await page.mouse.down({button:'right'});await page.mouse.up({button:'right'});assert.equal((await snap()).hands[1]?.id,3,'fall catches lower hold');await wait(800);for(let id=4;id<15;id++)await place(id,id%2);await release(1);await wait(1000);await release(0);await wait(2000);assert.equal((await snap()).won,true);console.log('LOWER HOLD RECOVERY + SUMMIT PASS');
await key('r');for(let id=0;id<=6;id++)await place(id,id%2);await release(1);await wait(1000);await release(0);await wait(1500);let rest=await snap();assert.equal(rest.player.y,rest.platforms[1].y-rest.footOffset);assert.ok(rest.player.ground);console.log('REST PLATFORM PASS');await place(15,0);await page.mouse.down({button:'right'});await wait(1000);let gap=false;for(let n=0;n<80;n++){let s=await snap(),a=s.shoulders[1],h=s.holds[7];if(Math.hypot(a.x-h.x,a.y-h.y)<s.reach-.5){gap=true;break;}await page.keyboard.down('a');await wait(20);}await page.keyboard.up('a');assert.ok(gap,'gap transfer can reach main route');await aim(7);await page.mouse.up({button:'right'});assert.equal((await snap()).hands[1]?.id,7);for(let id=8;id<15;id++)await place(id,id%2);await release(1);await wait(1000);await release(0);await wait(2000);assert.ok((await snap()).won,'gap route then summit');console.log('GAP ROUTE + SUMMIT PASS');
await key('r');await place(0,0);await aim(1);await page.mouse.down({button:'right'});await page.mouse.down({button:'left'});assert.deepEqual((await snap()).moving,[true,true]);assert.deepEqual((await snap()).hands,[null,null]);await page.mouse.up({button:'right'});assert.equal((await snap()).moving[0],true);await page.mouse.up({button:'left'});assert.deepEqual((await snap()).moving,[false,false]);
await key('r');await aim(0);await page.keyboard.down('q');assert.equal((await snap()).hands[0],null);await page.keyboard.up('q');assert.equal((await snap()).hands[0]?.id,0);await page.keyboard.down('e');await page.keyboard.up('e');assert.ok((await snap()).hands[1]);await wait(1500);let braced=await snap();for(let i=0;i<2;i++){const a=braced.shoulders[i],h=braced.holds[braced.hands[i].id];assert.ok(Math.hypot(h.x-a.x,h.y-a.y)<=braced.hands[i].length+.5);}
await page.mouse.down();await page.mouse.move(1200,500);let stretched=await snap(),a=stretched.shoulders[0],h=stretched.handPositions[0];assert.ok(Math.hypot(a.x-h.x,a.y-h.y)<=stretched.reach+.001,'free hand cannot stretch past reach');await page.screenshot({path:'tests/reaching.png'});await key('p');let frozen=await snap();await wait(1200);assert.deepEqual((await snap()).player,frozen.player);assert.deepEqual((await snap()).moving,[false,false]);await page.mouse.up();await key('p');assert.equal((await snap()).hands[0],null,'pause never creates a phantom grip');
await page.mouse.down({button:'right'});await page.evaluate(()=>dispatchEvent(new Event('blur')));assert.ok((await snap()).paused);await page.mouse.up({button:'right'});await page.locator('#resume').click();assert.deepEqual((await snap()).moving,[false,false]);await key('r');
await page.setViewportSize({width:600,height:750});await wait(200);await place(0,0);await page.screenshot({path:'tests/narrow.png'});await page.setViewportSize({width:1280,height:900});await key('r');await wait(200);await page.screenshot({path:'tests/start.png'});assert.deepEqual(errors,[]);console.log('INPUT CHORDS, KEYBOARD, REACH LIMIT, PAUSE, BLUR, RESET, RESIZE, ERRORS PASS');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});

